from django.urls import path
from . import views

# name of the Django app.
app_name = "AccountingSystem"

# URL configuration for Accounting_System.
urlpatterns = [
     path("", views.login_view, name="login_view"),
     path("index/", views.index, name="index"),
     path("login/", views.login_view, name="login"),
     path("forgot-password/", views.forgot_password, name="forgot_password"),
     path("logout/", views.logout_view, name="logout"),
     path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
     path('dashboard/teacher/', views.teacher_dashboard, name='teacher_dashboard'),
     path('dashboard/student/', views.student_dashboard, name='student_dashboard'),
     path('forbidden/', views.forbidden, name='forbidden'),
     path("accounts/", views.chart_of_accounts, name="accounts"),
     path("accounts_students/", views.chart_of_accounts_students, name="accounts_students"),
     path("accounts/pdf/", views.chart_of_accounts_pdf, name="accounts_pdf"),
     path("accounts_students/pdf/", views.chart_of_accounts_students_pdf, name="accounts_students_pdf"),
     path("journals/", views.journals, name="journals"),
     path("ledgers/", views.general_ledger, name="ledgers"),
     path("income-statement/", views.income_statement, name="income_statement"),
     path("balance-sheet/", views.balance_sheet, name="balance_sheet"),
     path("income-statement/pdf/", views.income_statement_pdf, name="income_statement_pdf"),
     path("balance-sheet/pdf/", views.balance_sheet_pdf, name="balance_sheet_pdf"),
     path("ledgers/download_pdf/", views.general_ledger_pdf, name="ledgers_pdf"),
     path("trial-balance/pdf/", views.trial_balance_pdf, name="trial_balance_pdf"),
     path("balance/", views.trial_balance, name="balance"),
     path('create_group/', views.create_group, name='create_group'),
     path("create_account/", views.create_account, name="create_account"),
     path("update_account/<int:id>/", views.update_account, name="update_account"),
     path("delete_account/<int:id>/", views.delete_account, name="delete_account"),
     path("insert_journals/", views.insert_journals, name="insert_journals"),
     path("update_journal_draft/<int:id>/", views.update_journal_draft, name="update_journal_draft"),
     path("delete_journal_draft/<int:id>/", views.delete_journal_draft, name="delete_journal_draft"),
     path("update_journal/<int:id>/", views.update_journal, name="update_journal"),
     path("delete_journal/<int:id>/", views.delete_journal, name="delete_journal"),
     path("approve_journal_draft/<int:id>/", views.approve_journal_draft, name="approve_journal_draft"),
     path("approve_all_user_drafts/<int:user_id>/", views.approve_all_user_drafts, name="approve_all_user_drafts"),
     path("ledger/account/<int:account_id>/transactions/", views.ledger_account_transactions, name="ledger_account_transactions"),
     path('trial-balance/json/', views.trial_balance_json, name='trial_balance_json'),
     path('journal_pdf/<int:id>/', views.journal_pdf, name='journal_pdf'),
     path('check_username_email_availability/', views.check_username_email_availability, name='check_username_email_availability'),
     path('create_user/', views.create_user, name='create_user'),
     path('teacher_create_user/', views.teacher_create_user, name='teacher_create_user'),
     path('teacher/sections/create/', views.create_student_section, name='create_student_section'),
     path('teacher/sections/assign/', views.assign_student_sections_bulk, name='assign_student_sections_bulk'),
     path('teacher/sections/assign-account-groups/', views.assign_account_groups_to_section, name='assign_account_groups_to_section'),
     path('teacher/sections/assign-self/', views.assign_teacher_to_sections, name='assign_teacher_to_sections'),
     path('teacher/account-groups/assign-self/', views.assign_account_groups_to_teacher, name='assign_account_groups_to_teacher'),
     path('admin/sections/assign-self/', views.assign_admin_to_sections, name='assign_admin_to_sections'),
     path('admin/sections/assign-teachers/', views.admin_assign_teachers_to_sections, name='admin_assign_teachers_to_sections'),
     path('admin/account-groups/assign-self/', views.assign_account_groups_to_admin, name='assign_account_groups_to_admin'),
     path('admin/sections/create/', views.admin_create_student_section, name='admin_create_student_section'),
     path('admin/sections/rename/', views.admin_rename_student_section, name='admin_rename_student_section'),
     path('admin/sections/advance/', views.admin_advance_section_students, name='admin_advance_section_students'),
     path('admin/sections/assign/', views.admin_assign_student_sections_bulk, name='admin_assign_student_sections_bulk'),
     path('admin/sections/assign-account-groups/', views.admin_assign_account_groups_to_section, name='admin_assign_account_groups_to_section'),
     path('toggle_user_active/', views.toggle_user_active, name='toggle_user_active'),
     path('change_user_password/', views.change_user_password, name='change_user_password'),
     path('change_own_password/', views.change_own_password, name='change_own_password'),
     path('update_user/', views.update_user, name='update_user'),
     path('delete_user/', views.delete_user, name='delete_user'),
     path('api/next_account_code/', views.get_next_account_code_api, name='get_next_account_code_api'),
     path('api/next_journal_code/', views.get_next_journal_code_api, name='get_next_journal_code_api'),
     
     # Journal History/Audit Trail URLs
     path('journal_history/<int:id>/', views.get_journal_history, name='journal_history'),
     path('journal_draft_history/<int:id>/', views.get_journal_draft_history, name='journal_draft_history'),
     
     # Journal Collaborator URLs
     path('add_collaborator/<int:id>/', views.add_collaborator, name='add_collaborator'),
     path('remove_collaborator/<int:id>/<int:collaborator_id>/', views.remove_collaborator, name='remove_collaborator'),
     path('add_collaborator_draft/<int:id>/', views.add_collaborator_draft, name='add_collaborator_draft'),
     path('remove_collaborator_draft/<int:id>/<int:collaborator_id>/', views.remove_collaborator_draft, name='remove_collaborator_draft'),
     path('get_available_collaborators/<int:journal_id>/<str:is_draft>/', views.get_available_collaborators, name='get_available_collaborators'),
     
     # Messaging URLs
     path('messages/send/', views.send_message, name='send_message'),
     path('messages/get/', views.get_messages, name='get_messages'),
     path('messages/unread/', views.get_unread_count, name='unread_count'),
     path('messages/delete/<int:message_id>/', views.delete_message, name='delete_message'),
     path('messages/download/<int:attachment_id>/', views.download_attachment, name='download_attachment'),
     path('api/users/', views.get_users_api, name='get_users_api'),

     # Task Management URLs
     path('tasks/send/', views.send_task, name='send_task'),
     path('tasks/get/', views.get_tasks, name='get_tasks'),
     path('tasks/submit/<int:task_id>/', views.submit_task, name='submit_task'),
     path('tasks/delete/<int:task_id>/', views.delete_task, name='delete_task'),
     path('tasks/download/<int:attachment_id>/', views.download_task_attachment, name='download_task_attachment'),
     path('tasks/submissions/download/<int:attachment_id>/', views.download_task_submission_attachment, name='download_task_submission_attachment'),
     path('api/teacher/students/', views.get_teacher_task_students_api, name='get_teacher_task_students_api'),
]