# Generated by Django 5.2.1 on 2025-10-14 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('group_name', models.TextField()),
                ('group_description', models.TextField()),
                ('group_type', models.TextField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')])),
            ],
            options={
                'db_table': 'account_groups',
            },
        ),
    ]
