# Generated by Django 5.2.1 on 2025-10-14 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0002_accountgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('account_name', models.TextField()),
                ('account_descriptions', models.TextField()),
            ],
        ),
    ]
