# Generated by Django 5.2.1 on 2025-10-14 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0003_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.today)),
                ('account_code', models.IntegerField(max_length=6, unique=True)),
                ('account_name', models.TextField()),
                ('account_type', models.TextField(choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expenses', 'Expenses')])),
            ],
            options={
                'db_table': 'accounts_table',
            },
        ),
        migrations.CreateModel(
            name='JournalEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
