# Generated by Django 5.2.1 on 2025-10-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0003_chartofaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='debit_credit',
            field=models.TextField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], null=True),
        ),
    ]
