# Generated by Django 5.2.1 on 2025-10-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0004_journalentry_chartofaccounts_debit_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroups',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
