# Generated by Django 5.2.1 on 2025-10-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0004_chartofaccounts_journalentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_code',
            field=models.TextField(max_length=10, unique=True),
        ),
    ]
