# Generated by Django 5.2.1 on 2025-10-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0005_alter_accountgroups_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='debit_credit',
        ),
        migrations.AddField(
            model_name='chartofaccounts',
            name='account_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_type',
            field=models.CharField(choices=[('Assets', 'Assets'), ('Liabilities', 'Liabilities'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expenses', 'Expenses')], max_length=255),
        ),
    ]
