# Generated by Django 5.2.1 on 2025-10-17 00:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0006_remove_chartofaccounts_debit_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_date_created', models.DateTimeField(auto_now_add=True)),
                ('entry_no', models.CharField(max_length=20, unique=True)),
                ('entry_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'journal_headers_table',
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Accounting_System_app.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table='journal_entries_table',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='journal_header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Accounting_System_app.journalheader'),
        ),
    ]
