# Generated by Django 5.2.1 on 2025-10-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0007_journalheader_journalentry_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalheader',
            name='journal_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
