# Generated by Django 5.2.1 on 2025-10-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0008_alter_chartofaccounts_account_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_code',
            field=models.BigIntegerField(max_length=6, unique=True),
        ),
    ]
