# Generated by Django 5.2.1 on 2025-12-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
