# Generated by Django 5.2.1 on 2025-12-11 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0010_alter_userprofile_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountgroups',
            name='group_type',
        ),
    ]
