# Generated by Django 5.2.1 on 2025-10-14 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0011_alter_chartofaccounts_account_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chartofaccounts',
            table=None,
        ),
    ]
