# Generated by Django 5.2.1 on 2025-12-11 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0011_remove_accountgroups_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='account_group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Accounting_System_app.accountgroups'),
        ),
    ]
