# Generated by Django 5.2.1 on 2025-12-11 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0012_chartofaccounts_account_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='account_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='Accounting_System_app.accountgroups'),
        ),
    ]
