# Generated by Django 5.2.1 on 2025-12-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0013_alter_chartofaccounts_account_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='account_group',
        ),
    ]
