# Generated by Django 5.2.1 on 2025-12-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0014_remove_chartofaccounts_account_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroupsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('group_name', models.TextField()),
                ('group_description', models.TextField()),
            ],
            options={
                'db_table': 'account_groups_table',
            },
        ),
    ]
