# Generated by Django 5.2.1 on 2025-12-11 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0015_accountgroupstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='group_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Accounting_System_app.accountgroups'),
        ),
    ]
