# Generated by Django 5.2.1 on 2025-12-11 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0016_chartofaccounts_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Accounting_System_app.accountgroups'),
        ),
    ]
