# Generated by Django 5.2.1 on 2025-12-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0017_alter_chartofaccounts_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccounts',
            name='group_name',
        ),
    ]
