# Generated by Django 5.2.1 on 2026-01-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0019_chartofaccounts_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalheader',
            name='group_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Accounting_System_app.accountgroups'),
        ),
    ]
