# Generated by Django 5.2.1 on 2026-02-20 08:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0022_journalheader_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalHeaderDrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_date_created', models.DateTimeField(auto_now_add=True)),
                ('entry_no', models.CharField(max_length=20, unique=True)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('journal_description', models.TextField(blank=True, null=True)),
                ('group_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Accounting_System_app.accountgroups')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_headers_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'journal_headers_table_drafts',
            },
        ),
    ]
