# Generated by Django 5.2.1 on 2026-02-20 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0023_journalheaderdrafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntryDrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=5, default=0.0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='Accounting_System_app.chartofaccounts')),
                ('journal_header', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='Accounting_System_app.journalheaderdrafts')),
            ],
            options={
                'db_table': 'journal_entries_table_drafts',
            },
        ),
    ]
