# Generated by Django 5.2.1 on 2026-02-20 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0024_journalentrydrafts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_journals', to=settings.AUTH_USER_MODEL)),
                ('journal_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='Accounting_System_app.journalheader')),
            ],
            options={
                'db_table': 'journal_collaborators',
                'unique_together': {('journal_header', 'collaborator')},
            },
        ),
        migrations.CreateModel(
            name='JournalDraftCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborated_journal_drafts', to=settings.AUTH_USER_MODEL)),
                ('journal_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='Accounting_System_app.journalheaderdrafts')),
            ],
            options={
                'db_table': 'journal_draft_collaborators',
                'unique_together': {('journal_header', 'collaborator')},
            },
        ),
    ]
