# Generated by Django 5.2.1 on 2026-03-05 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0027_studentsection_account_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_groups', models.ManyToManyField(blank=True, related_name='subjects', to='Accounting_System_app.accountgroups')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subjects', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ManyToManyField(blank=True, related_name='subjects', to='Accounting_System_app.studentsection')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['-created_at'],
            },
        ),
    ]
