# Generated by Django 5.2.1 on 2026-03-05 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting_System_app', '0029_journalaudittrail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
